[package]
name = "abrute"
version = "1.0.0"
edition = "2021"
authors = ["Daniel P. Clark <6ftdan@gmail.com>"]
description = "AESCrypt Brute force attempter."
documentation = "http://danielpclark.github.io/abrute/index.html"
homepage = "https://github.com/danielpclark/abrute"
repository = "https://github.com/danielpclark/abrute"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["crypto","text","cryptography","security"]
categories = ["cryptography"]

[dependencies]
aescry = "1.0"
array_tool = "1.0"
clap = { version = "4.3", features = ["cargo"] }
digits = "1.1"
lazy_static = "1.4"
libc = "0.2.125"
num_cpus = "1.16"
rayon = "1.10"
serde = "1.0"
serde_json = "1.0"
tiny_http = "0.12"
tempfile = "3.8"
